### ISSUE TITLE
unexpected characters in Blob class

### ISSUE THREAD

**Issue by loganpowell** [alex-kinokon/node-fetch-cjs#2]
Hi there!

I'm trying to use this library, but I'm getting an error thrown by the packaged `index-3a548b1a.js` file

```js
// starting line 147
const _Blob = class Blob {

	/** @type {Array.<(Blob|Uint8Array)>} */
	#parts = [];
	#type = '';
	#size = 0;

// ...
```

Error:
```sh
...\node_modules\node-fetch-commonjs\index-3a548b1a.js
  {:line 150, :column 1, :message "'}' expected"}
```
I've never seen this syntax. Any pointers?

**Comment by alex-kinokon** [comment]
Those are [private instance fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields), supported since Node 12.

**Comment by loganpowell** [comment]
gotcha... new to me! 🤷‍♂️ Thanks!
